/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/covered-car/covered_car_4k.gltf -r public 
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CoveredCar(props) {
  const { nodes, materials } = useGLTF('/covered-car/covered_car_4k.gltf')
  return (
    <group {...props} dispose={null} scale={3}>
      <mesh geometry={nodes.covered_car_wheel_01.geometry} material={materials.covered_car} position={[0.758, 0.3, 1.281]} />
      <mesh geometry={nodes.covered_car_wheel_02.geometry} material={materials.covered_car} position={[-0.682, 0.3, 1.281]} />
      <mesh geometry={nodes.covered_car_wheel_03.geometry} material={materials.covered_car} position={[-0.672, 0.3, -1.299]} />
      <mesh geometry={nodes.covered_car_wheel_04.geometry} material={materials.covered_car} position={[0.748, 0.3, -1.299]} />
      <mesh geometry={nodes.covered_car.geometry} material={materials.covered_car} position={[0.038, 0, 0.038]} />
    </group>
  )
}

useGLTF.preload('/covered-car/covered_car_4k.gltf')
