/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/laptop1/scene.gltf -r public 
Author: Thisal Pasindu (https://sketchfab.com/Thisal.Pasindu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-1-51aad26d1c544351ada8ff72a9d30b4d
Title: Laptop 1
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop1(props) {
  const { nodes, materials } = useGLTF('/laptop1/scene.gltf')
  return (
    <group {...props} dispose={null} scale={2}>
      <group position={[0, -0.002, 0.291]} rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[10.696, 23.154, 86.105]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-14.232, 15.511, 47.421]}>
            <mesh geometry={nodes.Keyboard001_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Keyboard001_Material005_0.geometry} material={materials['Material.005']} />
          </group>
          <group position={[40.583, 93.128, 94.553]} rotation={[-Math.PI / 2, 0, 0]} scale={[392.843, 133.854, 137.115]}>
            <mesh geometry={nodes.Bottom_panel_top_part002_Material022_0.geometry} material={materials['Material.022']} />
            <mesh geometry={nodes.Bottom_panel_top_part002_Material015_0.geometry} material={materials['Material.015']} />
          </group>
          <group position={[11.409, 17.559, 188.573]} rotation={[1.57, 1.57, -1.57]} scale={[8.712, 9.907, 32.747]}>
            <mesh geometry={nodes.Ports_Material017_0.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Ports_Material012_0.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Ports_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <mesh geometry={nodes.Bottom_panel001_Material021_0.geometry} material={materials['Material.021']} position={[12.246, 22.295, 0.315]} scale={[549.77, 163.666, 109.349]} />
          <mesh geometry={nodes.PwrBTN2_Material020_0.geometry} material={materials.material_0} position={[127.696, 22.996, 20.635]} rotation={[-Math.PI / 2, 0, 0]} scale={5.007} />
          <mesh geometry={nodes.PwrBtn3_Material019_0.geometry} material={materials['Material.019']} position={[127.696, 22.686, 20.635]} rotation={[-Math.PI / 2, 0, 0]} scale={5.934} />
          <mesh geometry={nodes.Audio_Plugs_Material018_0.geometry} material={materials['Material.018']} position={[-155.976, 17.749, 177.15]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-1.996, 1.996, 0.832]} />
          <mesh geometry={nodes.CamMain_Material016_0.geometry} material={materials['Material.016']} position={[11.539, 236.552, -31.881]} rotation={[-0.142, 0, 0]} scale={[10.091, 10.091, 16.081]} />
          <mesh geometry={nodes.CamGlass_Material014_0.geometry} material={materials['Material.014']} position={[11.328, 236.568, -31.28]} rotation={[-0.142, 0, 0]} scale={[11.857, 11.857, 18.895]} />
          <mesh geometry={nodes.CamRing_Material013_0.geometry} material={materials['Material.013']} position={[11.328, 236.516, -31.632]} rotation={[-0.142, 0, 0]} scale={[9.781, 9.781, 15.588]} />
          <mesh geometry={nodes.CamOutside_Material011_0.geometry} material={materials['Material.011']} position={[11.537, 236.572, -31.581]} rotation={[-0.142, 0, 0]} scale={[11.857, 11.857, 18.895]} />
          <mesh geometry={nodes.Knobs_Bottom_Material009_0.geometry} material={materials['Material.009']} position={[11.698, 5.323, 114.053]} rotation={[-1.57, 0, 0]} scale={[3.567, 3.567, 2.501]} />
          {/* Red line on bottom */}
          <mesh geometry={nodes.Bottom_panel_top_part005_Material008_0.geometry} material={materials['Material.008']} position={[-8.8, 22.252, 202.704]} rotation={[-Math.PI / 2, 0, 0]} scale={[250.063, 133.854, 137.115]} />
          <mesh geometry={nodes.Bottom_panel_top_part001_Material007_0.geometry} material={materials['Material.007']} position={[-8.792, 22.365, 182.118]} rotation={[-Math.PI / 2, 0, 0]} scale={[246.392, 141.101, 137.115]} />
          <mesh geometry={nodes.Rubbers_Material006_0.geometry} material={materials['Material.006']} position={[11.891, 134.811, -16.459]} rotation={[-0.149, 0, -Math.PI]} scale={[-100, 2.461, 100]} />
          <mesh geometry={nodes.Keyboard_Material005_0.geometry} material={materials['Material.005']} position={[10.696, 23.154, 86.105]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-14.232, 15.511, 47.421]} />
          <mesh geometry={nodes.Keyboardbackside_Material003_0.geometry} material={materials['Material.003']} position={[12.252, 22.661, 85.836]} rotation={[-Math.PI / 2, 0, 0]} scale={[169.628, 107.601, 107.062]} />
          <mesh geometry={nodes.Bottom_panel_top_part_Material001_0.geometry} material={materials['Material.001']} position={[11.791, 16.577, 114.276]} rotation={[-Math.PI / 2, 0, 0]} scale={[167.343, 107.601, 107.062]} />
          {/* Laptop keyboard border */}
          <mesh geometry={nodes.Bottom_panel_Material002_0.geometry} material={materials['Material.002']} position={[11.478, 10.495, 113.805]} scale={[99.03, 100, 100]} />
          {/* Monitor letter */}
          <mesh geometry={nodes.Screen_Material023_0.geometry} material={materials['Material.023']} position={[11.486, 134.435, -17.943]} rotation={[-0.151, 0, 0]} scale={[101.036, 86.293, 100]} />
          {/* Border color */}
          <mesh geometry={nodes.Top_panel_Material002_0.geometry} material={materials['Material.002']} position={[11.568, 133.991, -21.162]} rotation={[-0.151, 0, 0]} scale={[99.03, 100, 100]} />
          {/* Dell logo */}
          <mesh geometry={nodes.Text_Material024_0.geometry} material={materials['Material.024']} position={[-14.035, 25.845, -0.949]} scale={[13.213, 20.137, 34.152]} />
          <mesh geometry={nodes.Text001__0.geometry} material={materials['Text.001__0']} position={[50.9, 139.207, -25.94]} rotation={[Math.PI, 0.005, -Math.PI]} scale={[25.277, 31.54, 51.778]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/laptop1/scene.gltf')
